### PR TITLE
chart.ME : add legend.loc as a new parameter

### PR DESCRIPTION
**Pull request by anshul96go**
Solved issue #66

### CODE REVIEW

**Comment by braverock** [comment]
I'm happy to consider a patch in this direction, but we should be consistent in the naming conventions and functionality for `plot` and `plot.xts`

So the parameter should be `legend.loc` as in `plot.xts`

From the `plot.xts` documentation:
    
    legend.loc: places a legend into one of nine locations on the chart:
                bottomright, bottom, bottomleft, left, topleft, top,
                topright, right, or center. Default NULL does not draw a
                legend.

**Comment by anshul96go** [comment]
@braverock 
Should the working of parameter also remain the same? I was thinking of giving it bottomright value rather than NULL

**Comment by braverock** [comment]
I think a default of `bottomright` is fine.  The documentation would need to reflect this default and the NULL option (no legend)

**Comment by anshul96go** [comment]
@braverock  
Please verify the last commit

**Comment by anshul96go** [comment]
@braverock 
Should I start working on the application for GSOC and which channel should I use for communication?

**Comment by jaymon0703** [comment]
Thanks @anshul96go this PR is merged

**Comment by braverock** [comment]
@jaymon0703 has merged this pull request. Thanks @anshul96go  and @vi-to for the input.

This closes #77 and #66

**Comment by vi-to** [comment]
Hi, thank you very much for the feedback! About the pull request just merged, I would like to point out that it does not allow to plot `chart.ME` without a legend, that is to set `legend.loc = NULL`. It may be useful to do so because there may be trade points hidden by the legend. This option was allowed in pull request [#78](https://github.com/braverock/blotter/pull/78). Clearly, it is okay if you consider it to be a minor point and do not want it, the present remarks are just for the sake of development.

**Comment by braverock** [comment]
@vi-to thanks for your comment.

I encourage you to open a minimal (no whitespace, no extraneous stuff) pull request with a [clear and useful commit message](https://chris.beams.io/posts/git-commit/#seven-rules), and we would be happy to test and merge it.

It usually isn't a good idea to have dueling commits, and one of the challenges of your pull request was that it would have been better structured as a branch off the #77 pull request, so that everything would stay organized and traceable.

**Pull request merged**
